recipe: default.v1

language: ru

pipeline:
  - name: WhitespaceTokenizer
    case_sensitive: False
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 300
    batch_size: [20, 80]
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 300
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    # ambiguity_threshold: 0.01

policies:
  - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: TEDPolicy
    max_history: 4
    epochs: 300
  - name: RulePolicy
    # core_fallback_threshold: 0.9
    # core_fallback_action_name: "action_default_fallback"
    # enable_fallback_prediction: True
